name: Deploy to Cloud Run

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  SERVICE_NAME: whisper-api
  REGION: asia-northeast1
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/whisper-api/app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Container
        run: |
          gcloud builds submit \
            --tag "${IMAGE}:$GITHUB_SHA" \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: '${{ env.IMAGE }}:$GITHUB_SHA'
          flags: |
            --allow-unauthenticated
            --concurrency=10
            --cpu=1
            --memory=1Gi
            --timeout=60s
            --min-instances=0
